name: cron workflow 
on:
  schedule: 
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs: 
  cron-workflow-job:
    name: cron job
    runs-on: ubuntu-latest
    steps: 
     - name: bash command
       run: echo "cron workflow"
       shell: bash 